### ISSUE TITLE
NUMBER_OF_CITIES should not be a constant.

### ISSUE THREAD

**Issue by cohadar** [justradojko/RandomCityGenerator#3]
Your program is assuming that number of cities is 1500, this might not be true in the future, 
someone might add more cities to the cities.txt "database"

Recode loadFromFile to read cities until end of file.
Also number of cities will be in cityList.size(), there is no need for separate variable.

**Comment by justradojko** [comment]
Solved with commit e22748f9cd55549b716131a2330f3cdf09349ef6
