### ISSUE TITLE
makeRandomValidList is not efficient.

### ISSUE THREAD

**Issue by cohadar** [justradojko/RandomCityGenerator#4]
Your for loop is inserting more than required number of elements.
Using a C-style for loop is mostly a sign of bad code in languages that have collections.
Recode makeRandomValidList to use a subList method from List interface.
http://docs.oracle.com/javase/7/docs/api/java/util/List.html#subList(int,%20int)
Recode printRandomList  to use for-each loop over a randomList.
http://stackoverflow.com/questions/18410035/ways-to-iterate-over-a-list-in-java

**Comment by justradojko** [comment]
Hope that this issue is solved the way you wanted with latest commit (e22748f9cd55549b716131a2330f3cdf09349ef6)
