### ISSUE TITLE
makeRandomValidList is still not efficient

### ISSUE THREAD

**Issue by cohadar** [justradojko/RandomCityGenerator#5]
makeRandomValidList is still using for loop.
Try to think of a solution that uses only subList method (more than once).

It is also a bad practice to close issues until you are certain they are really "fixed"

**Comment by justradojko** [comment]
I'm not sure if there is a way to randomise cities using for-each loop with my current logic. In every iteration with for-each loop  I would copy each element of the cityList ArrayList into temporary var so I would lose a connection to original data source thus there is no way of changing it.

I'll try to come up with some solution that will meet your demand.

**Comment by justradojko** [comment]
Topic that will explain my point in more details: http://stackoverflow.com/questions/15844443/why-java-foreach-doesnt-change-element-value

**Comment by justradojko** [comment]
Is it a requirement to have separate List that will contain desired output? If I add quotes and random time during printout it could simplify the task

**Comment by justradojko** [comment]
So the solution would look something like this:

```
randomList = new ArrayList<String>(cityList.subList(startingPoint, startingPoint + n - (int)Math.ceil(n/5.0)));
randomList.addAll(randomList.subList(0, (int)Math.ceil(n/5.0)));
```

Quotes and random time is added in printRandomList method.
I noticed that this solution would need few ms more for N=1000

**Comment by cohadar** [comment]
Yes, the last one is correct. To achieve randomness you can shuffle the cityList itself before extracting subList!
We are not measuring milliseconds here, being efficient is about having shorter more precise code. Using standard methods instead of for loops is more efficient because it reduces the size of code, thus reducing the chance of errors, thus reducing the code maintenance time in the future. 
It is simply a better coding practice and a sign that you have mastered the standard library.

In fact it is very useful habit to always suspect your loops of being a bad code.
Whenever you do any kind of loop, ask yourself: is there a standard method that can do this same job in one line?
